name: mlst-seeker
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.11
  - pytest>=8.0.0
  - pandas>=2.2.0
  - requests>=2.31.0
  - tqdm>=4.66.2
  - mlst>=2.23.0
  - python-dateutil=2.8.2
  - google-cloud-bigquery
  - python-dotenv
  - pip